name: Build and push images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-n-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup pnpm
      # You may pin to the exact commit or the version.
      # uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d
      uses: pnpm/action-setup@v3.0.0
    - run: pnpm run build
    - name: Build the Docker image
      run: docker build -t minhhikari/hikari-aniblog:latest .
    - name: Push the "latest" image
      run: docker push "minhhikari/hikari-aniblog:latest"
    
    # steps:
    # - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
